name: Manter Streamlit Ativo

on:
  schedule:
    # Roda todos os dias Ã s 09:00 e 21:00 UTC
    - cron: '0 9,21 * * *'
  workflow_dispatch: # Permite rodar manualmente para testar

jobs:
  ping_app:
    runs-on: ubuntu-latest
    steps:
      - name: Acessar o App
        run: |
          curl -I -L -A "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36" https://revisor-encontros-bibli.streamlit.app/
